package org.naim.doctoo.AlgerieLocation.controller;

import java.util.List;

import org.naim.doctoo.AlgerieLocation.DAO.WilayaRepository;
import org.naim.doctoo.AlgerieLocation.model.Commune;
import org.naim.doctoo.AlgerieLocation.model.Wilaya;
import org.naim.doctoo.model.Doctor;
import org.naim.doctoo.model.Location;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;



@RestController
public class WilayaRs {
	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private WilayaRepository wilayaRep;



	
	
	@GetMapping(value = "/wilayas")
	public ResponseEntity<List<String>> getAllWilayas() {

		List<String> wilayas = (List<String>)wilayaRep.getAllWilaya();
		if (wilayas == null) {
			return new ResponseEntity(HttpStatus.BAD_REQUEST);
		} else {
			return new ResponseEntity<List<String>>(wilayas, HttpStatus.OK);
		}
	}
	

	
	@GetMapping(value = "/doctorss")
	public ResponseEntity<List<Doctor>> getAllProjetsFromOneDepartement() {

		List<Doctor> doctors = wilayaRep.findDoctorByWilayaId();
		if (doctors == null) {
			return new ResponseEntity(HttpStatus.NOT_FOUND);
		} else {
			return new ResponseEntity<List<Doctor>>(doctors, HttpStatus.OK);
		}

	}
	
}
